/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import classes.Carro;
import classes.Clientes;
import classes.Locacao;
import dados.CarrosDados;
import dados.ClientesDados;
import dados.LocacaoDados;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class FCadLocacao extends javax.swing.JDialog {

    private Locacao locTemp = null;
    private List<Carro> lstCarros = CarrosDados.lstCarros;
    private List<Clientes> lstClientes = ClientesDados.lstClientes; 

    public FCadLocacao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public Locacao execute(){
        cmbCarros.removeAllItems();
        cmbClientes.removeAllItems();        
        
        for(Carro car : lstCarros){
            cmbCarros.addItem(car.getModelo() + " - " + car.getPlaca());
        }
        
        for(Clientes cli : lstClientes){
            cmbClientes.addItem(cli.getNome() + " - " + cli.getCPFcnpj());
        }
        
        cmbCarros.repaint();
        cmbClientes.repaint();
        
        this.setVisible(true);
        return this.locTemp;
    }
    
    public String entrega(){

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy" + "HH:mm");

        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbClientes = new javax.swing.JComboBox<>();
        cmbCarros = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDtLoc = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHoraLoc = new javax.swing.JFormattedTextField();
        btnSalvarLoc = new javax.swing.JButton();
        btnCancelarLoc = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Locação");
        setResizable(false);

        cmbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClientesActionPerformed(evt);
            }
        });

        cmbCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCarrosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro de Locação");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Data de Locação:");

        try {
            txtDtLoc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Horário da Locação:");

        try {
            txtHoraLoc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnSalvarLoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvarLoc.setText("Salvar");
        btnSalvarLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarLocActionPerformed(evt);
            }
        });

        btnCancelarLoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelarLoc.setText("Cancelar");
        btnCancelarLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarLocActionPerformed(evt);
            }
        });

        jLabel4.setText("Clientes");

        jLabel5.setText("Carros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHoraLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDtLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmbCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCancelarLoc)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvarLoc))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(cmbCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDtLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoraLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelarLoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvarLoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClientesActionPerformed
        
    }//GEN-LAST:event_cmbClientesActionPerformed

    private void cmbCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCarrosActionPerformed

    }//GEN-LAST:event_cmbCarrosActionPerformed

    private void btnCancelarLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarLocActionPerformed
        this.locTemp = null;
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarLocActionPerformed

    private void btnSalvarLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarLocActionPerformed
        try{
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy" + "HH:mm");
            Locacao loc = new Locacao();
            
            String hr = txtHoraLoc.getText();
            
            Clientes cli = ClientesDados.lstClientes.get(cmbClientes.getSelectedIndex());
            Carro car = CarrosDados.lstCarros.get(cmbCarros.getSelectedIndex());
            
            boolean ver = true;
            
            if(LocacaoDados.lstLocacao.size() > 0){
                ver = true;
                
                for(Locacao locTeste : LocacaoDados.lstLocacao){

                    if(car == locTeste.getCarro() && locTeste.getDtEntrega() == null){
                        JOptionPane.showMessageDialog(this, "Este carro não está disponível!");
                        ver = false;
                    }
                }
            }
            if("  /  /    ".equals(txtDtLoc.getText())){
                JOptionPane.showMessageDialog(this,
                            "Insira a data de entrega.", "Atenção!", JOptionPane.WARNING_MESSAGE);
                ver=false;               
            }
            if("  :  ".equals(txtDtLoc.getText())){
                JOptionPane.showMessageDialog(this,
                            "Insira a hora de entrega.", "Atenção!", JOptionPane.WARNING_MESSAGE);
                ver=false;               
            }
            if(ver){
                loc.setCodigo(loc.getCodigo());
                loc.setCliente(cli);
                loc.setCarro(car);
                loc.setDtLocacao(sdf.parse(txtDtLoc.getText() + hr));
                loc.setDtEntrega(null);
                loc.setQtdDiasLocados(loc.getQtdDiasLocados());
                loc.setValorTotalLocacao(loc.getValorTotalLocacao());
                
            this.locTemp = loc;
            setVisible(false);
            }
            
        } catch(Exception ex){
            JOptionPane.showMessageDialog(this, 
                    "Não foi possível criar locacação \n\n" + ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarLocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FCadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FCadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FCadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FCadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FCadLocacao dialog = new FCadLocacao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarLoc;
    private javax.swing.JButton btnSalvarLoc;
    public javax.swing.JComboBox<String> cmbCarros;
    public javax.swing.JComboBox<String> cmbClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JFormattedTextField txtDtLoc;
    private javax.swing.JFormattedTextField txtHoraLoc;
    // End of variables declaration//GEN-END:variables
}
