/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import classes.Clientes;
import classes.PessoaFisica;
import classes.PessoaJuridica;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;


public class FCadCliente extends javax.swing.JDialog {

    private Clientes clienteTemp = null;
    private boolean alterar = false;
    
    
    public FCadCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public Clientes execute(){
        setVisible(true);
        return this.clienteTemp;
    }
    
    public Clientes execute(Clientes c) throws ParseException{
        this.alterar = true;
        this.clienteTemp = c;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        if( c instanceof PessoaFisica){
            rdbPJ.setEnabled(false);
            rdbPF.setSelected(true);
            rdbPF.setEnabled(false);
            
            lblCPFcnpj.setText("CPF");

            txtCPFcnpj.setText(c.getCPFcnpj());
            txtDtNasc.setText(sdf.format(c.getDtNasc()));
            
            lblDesconto.setVisible(false);
            txtDesconto.setVisible(false);
        
        }else{
            rdbPF.setEnabled(false);
            rdbPJ.setSelected(true);
            rdbPJ.setEnabled(false);
            
            lblCPFcnpj.setText("CNPJ");
            
            MaskFormatter formato = new MaskFormatter("##.###.###/####-##");
            DefaultFormatterFactory mascara = new DefaultFormatterFactory(formato);
            txtCPFcnpj.setFormatterFactory(mascara);
            
            txtCPFcnpj.setText(c.getCPFcnpj());
            txtDtNasc.setText(c.getDtNascPJ());
            
            lblDesconto.setVisible(true);
            txtDesconto.setVisible(true);
            lblDtNasc.setVisible(false);
            txtDtNasc.setVisible(false);
        }
                
        txtNome.setText(c.getNome());
        txtEndereco.setText(c.getEndereco());
        txtCNH.setText(c.getCNH());
        txtDesconto.setText(Double.toString(c.getDesconto()));

        setVisible(true);
        return clienteTemp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblCadCliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        rdbPF = new javax.swing.JRadioButton();
        rdbPJ = new javax.swing.JRadioButton();
        lblCPFcnpj = new javax.swing.JLabel();
        txtCPFcnpj = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblCNH = new javax.swing.JLabel();
        txtCNH = new javax.swing.JFormattedTextField();
        lblDesconto = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JTextField();
        btnSalvarCliente = new javax.swing.JButton();
        lblDtNasc = new javax.swing.JLabel();
        txtDtNasc = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnCancelarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente");
        setResizable(false);

        lblCadCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCadCliente.setText("Cadastro");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buttonGroup1.add(rdbPF);
        rdbPF.setText("Pessoa Física");
        rdbPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbPFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbPJ);
        rdbPJ.setText("Pessoa Jurídica");
        rdbPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbPJActionPerformed(evt);
            }
        });

        lblCPFcnpj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCPFcnpj.setText("CPF");

        try {
            txtCPFcnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Endereço");

        txtEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblCNH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCNH.setText("CNH");

        try {
            txtCNH.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblDesconto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDesconto.setText("Desconto");

        txtDesconto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnSalvarCliente.setText("Salvar");
        btnSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarClienteActionPerformed(evt);
            }
        });

        lblDtNasc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDtNasc.setText("Data de Nascimento");

        try {
            txtDtNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnCancelarCliente.setText("Cancelar");
        btnCancelarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome)
                            .addComponent(txtEndereco)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdbPF)
                                            .addComponent(rdbPJ, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCPFcnpj)
                                            .addComponent(txtCPFcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDtNasc)
                                            .addComponent(txtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 3, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCNH)
                                    .addComponent(txtCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDesconto)
                                    .addComponent(txtDesconto))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCadCliente)
                                .addGap(145, 145, 145))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCancelarCliente)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvarCliente)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCPFcnpj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCPFcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDtNasc)
                                .addGap(8, 8, 8)
                                .addComponent(txtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbPF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdbPJ)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCNH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblDesconto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdbPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbPFActionPerformed
        try{
        
            if(rdbPF.isSelected()){
                lblCPFcnpj.setText("CPF");
                lblCNH.setText("CNH");

                MaskFormatter cpf = new MaskFormatter("###.###.###-##");
                DefaultFormatterFactory formato = new DefaultFormatterFactory(cpf);
                txtCPFcnpj.setFormatterFactory(formato);
                
                lblDesconto.setVisible(false);
                txtDesconto.setVisible(false);
                
                lblDtNasc.setVisible(true);
                txtDtNasc.setVisible(true);

            }
        }catch (Exception ex){
            
        }
    }//GEN-LAST:event_rdbPFActionPerformed

    private void rdbPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbPJActionPerformed
        try{    
            if(rdbPJ.isSelected()){
                lblCPFcnpj.setText("CNPJ");
                lblCNH.setText("CNH responsável");
                
                MaskFormatter cnpj = new MaskFormatter("##.###.###/####-##");
                DefaultFormatterFactory formato = new DefaultFormatterFactory(cnpj);
                txtCPFcnpj.setFormatterFactory(formato);
                
                lblDtNasc.setVisible(false);
                txtDtNasc.setVisible(false);
                
                lblDesconto.setVisible(true);
                txtDesconto.setVisible(true);
 
            }
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_rdbPJActionPerformed

    private void btnCancelarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarClienteActionPerformed
        this.clienteTemp= null;
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarClienteActionPerformed

    private void btnSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarClienteActionPerformed
        try{
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Clientes cliente = null;
            
            boolean ver = true;
            
            if(rdbPF.isSelected()){
                ver= true;
                
                if(this.alterar){
                    cliente = this.clienteTemp;
                }else{
                    cliente = new PessoaFisica();
                }
                
                PessoaFisica pf = (PessoaFisica) cliente;
                
                if("   .   .   -  ".equals(txtCPFcnpj.getText())){
                    
                    JOptionPane.showMessageDialog(this,
                            "Insira um CPF.", "Atenção!", JOptionPane.WARNING_MESSAGE);
                    ver= false;
                }
                if(ver){
                    pf.setCpf(txtCPFcnpj.getText());
                    pf.setCnh(txtCNH.getText());
                    pf.setDtNascimento(sdf.parse(txtDtNasc.getText()));
                    
                    cliente.setNome(txtNome.getText());
                    cliente.setEndereco(txtEndereco.getText());
                    
                    this.clienteTemp = cliente;
                    setVisible(false);
                }
            }
            
            if(rdbPJ.isSelected()){
                ver = true;
                
                if(this.alterar){
                    cliente = this.clienteTemp;
                }else{
                    cliente = new PessoaJuridica();
                }
                
                PessoaJuridica pj = (PessoaJuridica) cliente;
                
                if("  .   .   /    -  ".equals(txtCPFcnpj.getText())){
                    JOptionPane.showMessageDialog(this,
                            "Insira um CNPJ.", "Atenção!", JOptionPane.WARNING_MESSAGE);
                    ver = false;
                }
                
                if(ver){
                    pj.setCnpj(txtCPFcnpj.getText());
                    pj.setCnhResponsavel(txtCNH.getText());
                    pj.setDescontoLocacao(Double.parseDouble(txtDesconto.getText()));
                    
                    cliente.setNome(txtNome.getText());
                    cliente.setEndereco(txtEndereco.getText());
                    
                    this.clienteTemp = cliente;
                    setVisible(false);
                }               
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, 
                    "Não foi possível criar/alterar cliente \n\n" + ex.getMessage(), "ERRO!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FCadCliente dialog = new FCadCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCliente;
    private javax.swing.JButton btnSalvarCliente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCNH;
    private javax.swing.JLabel lblCPFcnpj;
    public javax.swing.JLabel lblCadCliente;
    private javax.swing.JLabel lblDesconto;
    private javax.swing.JLabel lblDtNasc;
    private javax.swing.JRadioButton rdbPF;
    private javax.swing.JRadioButton rdbPJ;
    private javax.swing.JFormattedTextField txtCNH;
    private javax.swing.JFormattedTextField txtCPFcnpj;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JFormattedTextField txtDtNasc;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
